name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Decode certificate and provisioning profile
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > apple_cert.p12
          echo $APPLE_PROVISIONING_PROFILE | base64 --decode > provisioning_profile.mobileprovision

      - name: Install certificate
        run: |
          security create-keychain -p "" build.keychain
          security import apple_cert.p12 -k build.keychain -P "" -A
          security list-keychains -d user -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Resolve SPM dependencies
        run: xcodebuild -resolvePackageDependencies -project YourApp.xcodeproj

      - name: Build and test
        run: |
          xcodebuild -project YourApp.xcodeproj \
                     -scheme YourScheme \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
                     clean test | xcpretty
