name: CI

on:
  push:
    branches: 
    - master
  pull_request: 
    branches:
     - master

env: 
 DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Xcode Build
      run: xcodebuild -project CITest.xcodeproj -scheme CITest CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build

    - name: Xcode Test
      run: xcodebuild -project CITest.xcodeproj -scheme CITest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO test
