name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Resolve SPM dependencies
        run: xcodebuild -resolvePackageDependencies -project CITest.xcodeproj

      - name: Build and test
        run: |
          xcodebuild -project CITest.xcodeproj \
                     -scheme CITest \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
                     clean test \
                     -allowProvisioningUpdates | xcpretty
