name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build app
      run: bundle exec fastlane build

    - name: Run tests
      run: bundle exec fastlane test
