name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Install Cocoapods
      run: |
        brew install cocoapods
        pod install

    - name: Build app
      run: bundle exec fastlane build

    - name: Run tests
      run: bundle exec fastlane test
