# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Build and test
        run: |
          xcodebuild -workspace Office.xcworkspace \
                      -scheme Office \
                      -sdk iphonesimulator \
                      -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' \
                      clean build test
